name: mamission
description: "Application Flutter connectée à Firebase (auth, Firestore, storage, maps, messaging, stripe)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- INDISPENSABLE POUR LA ZONE D'INTERVENTION ---
  http: ^0.13.6


  # --- LOCALISATION (ALIGNE LE BIEN COMME ICI) ---
  flutter_localizations:
    sdk: flutter



  # --- Firebase core ---
  flutter_riverpod: ^2.5.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  flutter_animate: ^4.5.0 # <--- AJOUTEZ CETTE LIGNE
  geocoding: ^2.1.0
  google_place: ^0.4.7
  intl: 0.20.2
  google_fonts: ^4.0.4
  flutter_staggered_animations: ^1.1.1
  # --- LES NOUVEAUX AJOUTS (Alignés avec 'flutter') ---
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.3

  # --- Routing & UI ---
  go_router: ^14.2.0
  google_maps_flutter: ^2.13.1
  flutter_stripe: ^11.5.0
  cupertino_icons: ^1.0.8

  # --- Géolocalisation ---
  geolocator: ^11.1.0
  location: ^7.0.1

  # --- Google API & médias ---
  image_picker: ^1.1.2      # upload photo profil

  # --- Outils divers ---
  freezed_annotation: ^2.4.4
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.1.2 # <-- AJOUTEZ ÇA
  cloud_functions: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/mission_marker.png
    - assets/icons/mission_marker_halo.png
    - assets/icons/user_marker_red.png
    - assets/images/
    - assets/config/map_style.json
    - assets/fonts/manrope/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope[wght].ttf


